CREATE DATABASE IF NOT EXISTS booknest_auth;
CREATE DATABASE IF NOT EXISTS booknest_book;
CREATE DATABASE IF NOT EXISTS booknest_cart;
CREATE DATABASE IF NOT EXISTS booknest_order;
CREATE DATABASE IF NOT EXISTS booknest_wallet;
CREATE DATABASE IF NOT EXISTS booknest_review;
CREATE DATABASE IF NOT EXISTS booknest_notification;
